services:
    # Controller
    RevisionTen\CMS_AMP\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        exclude: '../../Controller/{FrontendController.php}'
        tags: ['controller.service_arguments']
    RevisionTen\CMS_AMP\Controller\FrontendController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
        arguments:
            $project_dir: '%kernel.project_dir%'
            $config: '%cms_amp%'
    # Twig
    RevisionTen\CMS_AMP\Twig\CmsAmpExtension:
        autowire: true
        public: true
        tags: [twig.extension]
        arguments:
            $cms_amp_config: '%cms_amp%'
    RevisionTen\CMS_AMP\Twig\CssInlinerExtension:
        autowire: true
        public: true
        tags: [twig.extension]
