cms:
    site_name: 'CMS AMP'
    menu_items:
        Page:
            class: RevisionTen\CMS\Form\Menu\Page
            template: 'CmsAmpBundle::Menu/Items/page.html.twig'
        Link:
            class: RevisionTen\CMS\Form\Menu\Link
            template: 'CmsAmpBundle::Menu/Items/link.html.twig'
        Divider:
            class: RevisionTen\CMS\Form\Menu\Divider
            template: 'CmsAmpBundle::Menu/Items/divider.html.twig'
    page_elements:
        Section:
            class: RevisionTen\CMS\Form\Elements\Section
            type: 'Section'
            template: 'CmsAmpBundle::Elements/section.html.twig'
            icon: 'fa fa-th-large'
            children:
                - 'Row'
        Carousel:
            class: RevisionTen\CMS_AMP\Form\Elements\Carousel
            template: 'CmsAmpBundle::Elements/carousel.html.twig'
            public: true
            icon: 'fa fa-object-group'
            children:
                - 'all'
        Image:
            class: RevisionTen\CMS_AMP\Form\Elements\Image
            template: 'CmsAmpBundle::Elements/image.html.twig'
            public: true
            icon: 'fa fa-image'
        AmpIframe:
            class: RevisionTen\CMS_AMP\Form\Elements\AmpIframe
            template: 'CmsAmpBundle::Elements/amp-iframe.html.twig'
            public: true
            icon: 'fas fa-vector-square'
