cms:
    site_name: 'CMS AMP'
    page_elements:
        Section:
            class: RevisionTen\CMS\Form\Elements\Section
            type: 'Section'
            template: 'CmsAmpBundle::Elements/section.html.twig'
            icon: 'fa fa-th-large'
            children:
                - 'Row'
        Carousel:
            class: RevisionTen\CMS_AMP\Form\Elements\Carousel
            template: 'CmsAmpBundle::Elements/carousel.html.twig'
            public: true
            icon: 'fa fa-object-group'
            children:
                - 'all'
        Image:
            class: RevisionTen\CMS_AMP\Form\Elements\Image
            template: 'CmsAmpBundle::Elements/image.html.twig'
            public: true
            icon: 'fa fa-image'
